// Runtime Simulator - Proves generated configs are executable
// Generates actual code artifacts from the pipeline output

export class RuntimeSimulator {
  // Generate all executable artifacts from pipeline output
  static generate(configs) {
    const { ui, api, db, auth, businessLogic } = configs;
    const results = {
      success: true,
      artifacts: {},
      errors: [],
      summary: {}
    };

    try {
      results.artifacts.sql = this.generateSQL(db);
      results.summary.tables = db?.tables?.length || 0;
    } catch (e) {
      results.errors.push({ layer: 'db', error: e.message });
    }

    try {
      results.artifacts.expressRoutes = this.generateExpressRoutes(api, auth);
      results.summary.endpoints = api?.endpoints?.length || 0;
    } catch (e) {
      results.errors.push({ layer: 'api', error: e.message });
    }

    try {
      results.artifacts.reactApp = this.generateReactApp(ui, api);
      results.summary.pages = ui?.pages?.length || 0;
    } catch (e) {
      results.errors.push({ layer: 'ui', error: e.message });
    }

    try {
      results.artifacts.authMiddleware = this.generateAuthMiddleware(auth);
      results.summary.roles = auth?.roles?.length || 0;
    } catch (e) {
      results.errors.push({ layer: 'auth', error: e.message });
    }

    try {
      results.artifacts.businessRules = this.generateBusinessRules(businessLogic);
      results.summary.rules = businessLogic?.rules?.length || 0;
    } catch (e) {
      results.errors.push({ layer: 'businessLogic', error: e.message });
    }

    results.success = results.errors.length === 0;
    return results;
  }

  // Generate SQL CREATE TABLE statements
  static generateSQL(db) {
    if (!db?.tables?.length) return '-- No tables defined';
    const lines = [
      '-- Auto-generated by AppForge Runtime',
      `-- Dialect: ${db.dialect || 'postgresql'}`,
      `-- Generated: ${new Date().toISOString()}`,
      ''
    ];

    for (const table of db.tables) {
      lines.push(`CREATE TABLE IF NOT EXISTS "${table.name}" (`);
      const colDefs = [];

      for (const col of table.columns) {
        let def = `  "${col.name}" ${this._sqlType(col.type, col)}`;
        if (col.primaryKey) def += ' PRIMARY KEY';
        if (col.unique && !col.primaryKey) def += ' UNIQUE';
        if (col.nullable === false) def += ' NOT NULL';
        if (col.default !== undefined && col.default !== null) {
          def += ` DEFAULT ${typeof col.default === 'string' ? `'${col.default}'` : col.default}`;
        }
        colDefs.push(def);
      }

      // Foreign keys
      for (const col of table.columns) {
        if (col.references) {
          colDefs.push(`  FOREIGN KEY ("${col.name}") REFERENCES "${col.references.table}"("${col.references.column || 'id'}") ON DELETE ${col.references.onDelete || 'CASCADE'}`);
        }
      }

      lines.push(colDefs.join(',\n'));
      lines.push(');');
      lines.push('');

      // Indexes
      if (table.indexes) {
        for (const idx of table.indexes) {
          const idxName = `idx_${table.name}_${idx.columns.join('_')}`;
          lines.push(`CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX IF NOT EXISTS "${idxName}" ON "${table.name}" (${idx.columns.map(c => `"${c}"`).join(', ')});`);
        }
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  static _sqlType(type, col) {
    const map = {
      uuid: 'UUID DEFAULT gen_random_uuid()',
      varchar: 'VARCHAR(255)',
      text: 'TEXT',
      integer: 'INTEGER',
      bigint: 'BIGINT',
      boolean: 'BOOLEAN',
      timestamp: 'TIMESTAMP WITH TIME ZONE',
      jsonb: 'JSONB',
      decimal: 'DECIMAL(10,2)',
      date: 'DATE',
      serial: 'SERIAL',
      enum: col?.enumValues ? `VARCHAR(50) CHECK ("${col.name}" IN (${col.enumValues.map(v => `'${v}'`).join(', ')}))` : 'VARCHAR(50)'
    };
    return map[type] || 'VARCHAR(255)';
  }

  // Generate Express.js route handlers
  static generateExpressRoutes(api, auth) {
    if (!api?.endpoints?.length) return '// No endpoints defined';
    const lines = [
      "// Auto-generated by AppForge Runtime",
      "import express from 'express';",
      "import { authenticate, authorize } from './middleware/auth.js';",
      "",
      "const router = express.Router();",
      ""
    ];

    for (const ep of api.endpoints) {
      const method = ep.method.toLowerCase();
      const middlewares = [];

      if (ep.auth?.required) {
        middlewares.push('authenticate');
        if (ep.auth.roles?.length) {
          middlewares.push(`authorize(${JSON.stringify(ep.auth.roles)})`);
        }
      }

      const mwStr = middlewares.length ? middlewares.join(', ') + ', ' : '';
      const routePath = ep.path.replace('/api/v1', '');

      lines.push(`// ${ep.description || ep.id}`);
      lines.push(`router.${method}('${routePath}', ${mwStr}async (req, res) => {`);
      lines.push(`  try {`);

      switch (ep.operation) {
        case 'readAll':
          lines.push(`    const items = await db.${ep.relatedEntity}.findAll(req.query);`);
          lines.push(`    res.json({ data: items, total: items.length });`);
          break;
        case 'read':
          lines.push(`    const item = await db.${ep.relatedEntity}.findById(req.params.id);`);
          lines.push(`    if (!item) return res.status(404).json({ error: 'Not found' });`);
          lines.push(`    res.json({ data: item });`);
          break;
        case 'create':
          lines.push(`    const created = await db.${ep.relatedEntity}.create(req.body);`);
          lines.push(`    res.status(201).json({ data: created });`);
          break;
        case 'update':
          lines.push(`    const updated = await db.${ep.relatedEntity}.update(req.params.id, req.body);`);
          lines.push(`    res.json({ data: updated });`);
          break;
        case 'delete':
          lines.push(`    await db.${ep.relatedEntity}.delete(req.params.id);`);
          lines.push(`    res.status(204).send();`);
          break;
        case 'login':
          lines.push(`    const { email, password } = req.body;`);
          lines.push(`    const user = await auth.login(email, password);`);
          lines.push(`    res.json({ data: { user, token: auth.generateToken(user) } });`);
          break;
        case 'register':
          lines.push(`    const newUser = await auth.register(req.body);`);
          lines.push(`    res.status(201).json({ data: { user: newUser, token: auth.generateToken(newUser) } });`);
          break;
        default:
          lines.push(`    // Custom handler for: ${ep.operation}`);
          lines.push(`    res.json({ message: 'Not implemented' });`);
      }

      lines.push(`  } catch (error) {`);
      lines.push(`    res.status(500).json({ error: error.message });`);
      lines.push(`  }`);
      lines.push(`});`);
      lines.push('');
    }

    lines.push('export default router;');
    return lines.join('\n');
  }

  // Generate React app preview (HTML)
  static generateReactApp(ui, api) {
    if (!ui?.pages?.length) return '<!-- No pages defined -->';

    const navItems = (ui.navigation?.items || [])
      .map(item => `<a href="#${item.route}" class="nav-item" data-roles="${(item.roles||[]).join(',')}">${item.icon ? `<span class="icon">${item.icon}</span>` : ''}${item.label}</a>`)
      .join('\n        ');

    const pages = ui.pages.map(page => {
      const components = (page.components || []).map(comp => {
        switch (comp.type) {
          case 'stat-card':
            return `<div class="stat-card"><h3>${comp.props?.title || 'Stat'}</h3><p class="stat-value">${comp.props?.value || '0'}</p></div>`;
          case 'table':
            return `<div class="data-table"><h3>${comp.props?.title || 'Data'}</h3><table><thead><tr>${(comp.props?.columns || ['ID', 'Name']).map(c => `<th>${c}</th>`).join('')}</tr></thead><tbody><tr><td colspan="${(comp.props?.columns || ['ID', 'Name']).length}">Data loaded from ${comp.dataSource?.endpoint || 'API'}</td></tr></tbody></table></div>`;
          case 'form':
            return `<div class="form-card"><h3>${comp.props?.title || 'Form'}</h3><form>${(comp.props?.fields || [{ name: 'field', type: 'text' }]).map(f => `<div class="form-group"><label>${f.label || f.name}</label><input type="${f.type || 'text'}" name="${f.name}" placeholder="${f.placeholder || ''}" /></div>`).join('')}<button type="submit">Submit</button></form></div>`;
          case 'chart':
            return `<div class="chart-card"><h3>${comp.props?.title || 'Chart'}</h3><div class="chart-placeholder">📊 ${comp.props?.chartType || 'bar'} chart</div></div>`;
          case 'card':
            return `<div class="content-card"><h3>${comp.props?.title || 'Card'}</h3><p>${comp.props?.content || 'Content'}</p></div>`;
          case 'list':
            return `<div class="list-card"><h3>${comp.props?.title || 'List'}</h3><ul><li>Item from ${comp.dataSource?.endpoint || 'API'}</li></ul></div>`;
          case 'hero':
            return `<div class="hero"><h1>${comp.props?.title || 'Welcome'}</h1><p>${comp.props?.subtitle || ''}</p></div>`;
          default:
            return `<div class="component component-${comp.type}">[${comp.type}: ${comp.id}]</div>`;
        }
      }).join('\n        ');

      return `
      <section class="page" id="page-${page.id}" data-route="${page.route}" data-roles="${(page.requiredRoles || []).join(',')}">
        <h2 class="page-title">${page.name}</h2>
        <div class="page-content layout-${page.layout}">
        ${components}
        </div>
      </section>`;
    }).join('\n');

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${ui.theme?.appName || 'Generated App'}</title>
  <style>
    :root { --primary: ${ui.theme?.primaryColor || '#3B82F6'}; --bg: ${ui.theme?.mode === 'dark' ? '#0f172a' : '#f8fafc'}; --text: ${ui.theme?.mode === 'dark' ? '#e2e8f0' : '#1e293b'}; --card-bg: ${ui.theme?.mode === 'dark' ? '#1e293b' : '#ffffff'}; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', system-ui, sans-serif; background: var(--bg); color: var(--text); display: flex; min-height: 100vh; }
    .sidebar { width: 240px; background: var(--card-bg); padding: 1rem; border-right: 1px solid #e2e8f0; }
    .sidebar h1 { font-size: 1.2rem; color: var(--primary); margin-bottom: 1.5rem; }
    .nav-item { display: block; padding: 0.6rem 1rem; margin: 0.2rem 0; border-radius: 8px; text-decoration: none; color: var(--text); transition: background 0.2s; }
    .nav-item:hover { background: color-mix(in srgb, var(--primary) 15%, transparent); }
    .main { flex: 1; padding: 2rem; }
    .page-title { font-size: 1.5rem; margin-bottom: 1.5rem; }
    .layout-dashboard .page-content { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1rem; }
    .stat-card, .data-table, .form-card, .chart-card, .content-card, .list-card { background: var(--card-bg); border-radius: 12px; padding: 1.5rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .stat-value { font-size: 2rem; font-weight: 700; color: var(--primary); margin-top: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #e2e8f0; }
    .form-group { margin-bottom: 1rem; }
    .form-group label { display: block; font-weight: 500; margin-bottom: 0.3rem; }
    .form-group input { width: 100%; padding: 0.5rem; border: 1px solid #cbd5e1; border-radius: 6px; }
    button { background: var(--primary); color: white; border: none; padding: 0.6rem 1.5rem; border-radius: 6px; cursor: pointer; }
    .hero { text-align: center; padding: 3rem; background: linear-gradient(135deg, var(--primary), #8b5cf6); color: white; border-radius: 12px; }
    .hero h1 { font-size: 2.5rem; }
    .chart-placeholder { padding: 2rem; text-align: center; font-size: 3rem; }
  </style>
</head>
<body>
  <nav class="sidebar">
    <h1>🔷 App</h1>
    ${navItems}
  </nav>
  <main class="main">
    ${pages}
  </main>
</body>
</html>`;
  }

  // Generate auth middleware code
  static generateAuthMiddleware(auth) {
    if (!auth) return '// No auth config';
    const lines = [
      "// Auto-generated Auth Middleware",
      "import jwt from 'jsonwebtoken';",
      "",
      `const JWT_SECRET = process.env.JWT_SECRET || 'app-secret-key';`,
      `const ROLES = ${JSON.stringify(auth.roles?.map(r => r.name) || [])};`,
      "",
      "export function authenticate(req, res, next) {",
      "  const token = req.headers.authorization?.replace('Bearer ', '');",
      "  if (!token) return res.status(401).json({ error: 'Authentication required' });",
      "  try {",
      "    req.user = jwt.verify(token, JWT_SECRET);",
      "    next();",
      "  } catch {",
      "    res.status(401).json({ error: 'Invalid token' });",
      "  }",
      "}",
      "",
      "export function authorize(allowedRoles) {",
      "  return (req, res, next) => {",
      "    if (!req.user) return res.status(401).json({ error: 'Not authenticated' });",
      "    if (!allowedRoles.includes(req.user.role)) {",
      "      return res.status(403).json({ error: 'Insufficient permissions' });",
      "    }",
      "    next();",
      "  };",
      "}",
      "",
    ];

    // Generate permission checks
    if (auth.permissions?.length) {
      lines.push("export const permissions = {");
      for (const perm of auth.permissions) {
        lines.push(`  '${perm.resource}': ${JSON.stringify(perm.actions)},`);
      }
      lines.push("};");
      lines.push("");
      lines.push("export function checkPermission(resource, action) {");
      lines.push("  return (req, res, next) => {");
      lines.push("    const allowed = permissions[resource]?.[action] || [];");
      lines.push("    if (!allowed.includes(req.user?.role)) {");
      lines.push("      return res.status(403).json({ error: `No ${action} permission on ${resource}` });");
      lines.push("    }");
      lines.push("    next();");
      lines.push("  };");
      lines.push("}");
    }

    return lines.join('\n');
  }

  // Generate business rules as executable functions
  static generateBusinessRules(logic) {
    if (!logic?.rules?.length) return '// No business rules defined';
    const lines = [
      "// Auto-generated Business Rules Engine",
      "",
      "export class BusinessRulesEngine {",
      "  constructor(db, notifier) {",
      "    this.db = db;",
      "    this.notifier = notifier;",
      "  }",
      "",
    ];

    for (const rule of logic.rules) {
      lines.push(`  // ${rule.name}: ${rule.description || ''}`);
      lines.push(`  async execute_${rule.id.replace(/[^a-zA-Z0-9]/g, '_')}(context) {`);

      // Generate conditions
      if (rule.conditions?.length) {
        const conditions = rule.conditions.map(c => {
          const ops = { eq: '===', neq: '!==', gt: '>', lt: '<', gte: '>=', lte: '<=' };
          const op = ops[c.operator] || '===';
          return `context.${c.field} ${op} ${JSON.stringify(c.value)}`;
        });
        lines.push(`    if (!(${conditions.join(' && ')})) return;`);
      }

      // Generate actions
      for (const action of (rule.actions || [])) {
        switch (action.type) {
          case 'notify':
            lines.push(`    await this.notifier.send('${action.target}', ${JSON.stringify(action.params || {})});`);
            break;
          case 'update':
            lines.push(`    await this.db.${action.target}.update(context.id, ${JSON.stringify(action.params || {})});`);
            break;
          case 'restrict':
            lines.push(`    throw new Error('Access restricted: ${rule.name}');`);
            break;
          default:
            lines.push(`    // ${action.type}: ${action.target}`);
        }
      }

      lines.push(`  }`);
      lines.push('');
    }

    lines.push('}');
    return lines.join('\n');
  }
}
