// Schema Validator & Repair Engine
// Validates pipeline outputs against JSON Schemas and attempts auto-repair
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import {
  intentSchema, designSchema, uiSchema, apiSchema,
  dbSchema, authSchema, businessLogicSchema
} from '../schemas/definitions.js';

const ajv = new Ajv({ allErrors: true, strict: false, coerceTypes: true });
addFormats(ajv);

// Compile validators
const validators = {
  intent: ajv.compile(intentSchema),
  design: ajv.compile(designSchema),
  ui: ajv.compile(uiSchema),
  api: ajv.compile(apiSchema),
  db: ajv.compile(dbSchema),
  auth: ajv.compile(authSchema),
  businessLogic: ajv.compile(businessLogicSchema),
};

export class SchemaValidator {
  // Validate data against a named schema
  static validate(schemaName, data) {
    const validator = validators[schemaName];
    if (!validator) throw new Error(`Unknown schema: ${schemaName}`);

    const valid = validator(data);
    return {
      valid,
      errors: valid ? [] : validator.errors.map(e => ({
        path: e.instancePath || '/',
        message: e.message,
        keyword: e.keyword,
        params: e.params,
        schemaPath: e.schemaPath
      }))
    };
  }

  // Validate and auto-repair
  static validateAndRepair(schemaName, data) {
    const initial = this.validate(schemaName, data);
    if (initial.valid) {
      return { valid: true, data, repairs: [], errors: [] };
    }

    // Attempt repairs
    const repairs = [];
    let repaired = JSON.parse(JSON.stringify(data)); // deep clone

    for (const error of initial.errors) {
      const repair = RepairEngine.repair(repaired, error, schemaName);
      if (repair.fixed) {
        repairs.push(repair);
        repaired = repair.data;
      }
    }

    // Re-validate after repairs
    const postRepair = this.validate(schemaName, repaired);
    return {
      valid: postRepair.valid,
      data: repaired,
      repairs,
      errors: postRepair.errors
    };
  }
}

// Repair Engine - attempts to fix common validation errors
class RepairEngine {
  static repair(data, error, schemaName) {
    const path = error.path.split('/').filter(Boolean);

    switch (error.keyword) {
      case 'required':
        return this._addMissingField(data, path, error.params.missingProperty, schemaName);
      case 'type':
        return this._coerceType(data, path, error.params.type);
      case 'enum':
        return this._fixEnum(data, path, error.params.allowedValues);
      case 'minLength':
        return this._fixMinLength(data, path);
      case 'minItems':
        return this._fixMinItems(data, path, schemaName);
      case 'pattern':
        return this._fixPattern(data, path, error.params.pattern);
      case 'additionalProperties':
        return this._removeExtraProps(data, path, error.params.additionalProperty);
      default:
        return { fixed: false, data, description: `Cannot auto-repair: ${error.keyword}` };
    }
  }

  static _addMissingField(data, path, fieldName, schemaName) {
    const target = this._navigateTo(data, path);
    if (!target) return { fixed: false, data, description: `Cannot navigate to ${path.join('.')}` };

    // Determine default based on field name and context
    const defaults = {
      appName: 'Untitled App',
      appDescription: 'An application generated by AppForge',
      appType: 'custom',
      features: [{ name: 'core', description: 'Core feature', priority: 'core', category: 'data' }],
      entities: [{ name: 'item', description: 'Default entity', attributes: ['id', 'name'] }],
      roles: [{ name: 'user', capabilities: ['read'], description: 'Default user' }],
      businessRules: [],
      assumptions: [],
      ambiguities: [],
      architecture: { type: 'monolithic', frontend: 'spa', backend: 'rest', database: 'postgresql' },
      pages: [{ name: 'Home', purpose: 'Landing page', accessRoles: ['user'], components: [], dataEntities: [] }],
      authFlows: [{ type: 'login', fields: ['email', 'password'] }],
      businessFlows: [],
      navigation: { type: 'sidebar', items: [] },
      theme: { primaryColor: '#3B82F6', mode: 'light' },
      baseUrl: '/api/v1',
      endpoints: [],
      dialect: 'postgresql',
      tables: [],
      strategy: 'jwt',
      permissions: [],
      rules: [],
      id: `${fieldName}_${Date.now()}`,
      name: fieldName,
      description: '',
      type: 'string',
      required: false,
      route: '/',
      layout: 'dashboard',
      components: [],
      method: 'GET',
      auth: { required: true, roles: [] },
      relatedEntity: 'unknown',
      operation: 'custom',
      columns: [{ name: 'id', type: 'uuid', primaryKey: true }],
      trigger: { type: 'event', source: 'system' },
      actions: [{ type: 'notify', target: 'system' }],
      conditions: [],
      effect: 'allow',
      path: '/',
    };

    target[fieldName] = defaults[fieldName] ?? (fieldName.endsWith('s') ? [] : '');
    return { fixed: true, data, description: `Added missing field: ${fieldName} at ${path.join('.') || 'root'}` };
  }

  static _coerceType(data, path, expectedType) {
    const parent = path.length > 1 ? this._navigateTo(data, path.slice(0, -1)) : data;
    const key = path[path.length - 1];
    if (!parent || key === undefined) return { fixed: false, data, description: 'Cannot coerce type' };

    const val = parent[key];
    try {
      switch (expectedType) {
        case 'string': parent[key] = String(val); break;
        case 'number':
        case 'integer': parent[key] = Number(val); break;
        case 'boolean': parent[key] = Boolean(val); break;
        case 'array': parent[key] = Array.isArray(val) ? val : [val]; break;
        case 'object': parent[key] = typeof val === 'object' ? val : {}; break;
        default: return { fixed: false, data, description: `Unknown type: ${expectedType}` };
      }
      return { fixed: true, data, description: `Coerced ${path.join('.')} to ${expectedType}` };
    } catch {
      return { fixed: false, data, description: 'Type coercion failed' };
    }
  }

  static _fixEnum(data, path, allowedValues) {
    const parent = path.length > 1 ? this._navigateTo(data, path.slice(0, -1)) : data;
    const key = path[path.length - 1];
    if (!parent || !allowedValues?.length) return { fixed: false, data, description: 'Cannot fix enum' };

    const current = String(parent[key]).toLowerCase();
    // Try fuzzy match
    const match = allowedValues.find(v => v.toLowerCase() === current || current.includes(v.toLowerCase()));
    parent[key] = match || allowedValues[0];
    return { fixed: true, data, description: `Fixed enum ${path.join('.')}: ${current} → ${parent[key]}` };
  }

  static _fixMinLength(data, path) {
    const parent = path.length > 1 ? this._navigateTo(data, path.slice(0, -1)) : data;
    const key = path[path.length - 1];
    if (!parent) return { fixed: false, data, description: 'Cannot fix minLength' };
    if (!parent[key]) parent[key] = 'auto-generated';
    return { fixed: true, data, description: `Fixed minLength at ${path.join('.')}` };
  }

  static _fixMinItems(data, path, schemaName) {
    const parent = path.length > 0 ? this._navigateTo(data, path) : data;
    if (!Array.isArray(parent)) return { fixed: false, data, description: 'Not an array' };
    // Add a default item
    parent.push({ name: 'default', description: 'Auto-generated' });
    return { fixed: true, data, description: `Added default item to ${path.join('.')}` };
  }

  static _fixPattern(data, path, pattern) {
    const parent = path.length > 1 ? this._navigateTo(data, path.slice(0, -1)) : data;
    const key = path[path.length - 1];
    if (!parent) return { fixed: false, data, description: 'Cannot fix pattern' };
    // Common fix: routes must start with /
    if (pattern === '^/' && !String(parent[key]).startsWith('/')) {
      parent[key] = '/' + parent[key];
      return { fixed: true, data, description: `Fixed pattern: prepended / to ${path.join('.')}` };
    }
    return { fixed: false, data, description: `Cannot fix pattern: ${pattern}` };
  }

  static _removeExtraProps(data, path, prop) {
    const target = this._navigateTo(data, path);
    if (target && prop in target) {
      delete target[prop];
      return { fixed: true, data, description: `Removed additional property: ${prop} at ${path.join('.')}` };
    }
    return { fixed: false, data, description: 'Cannot remove property' };
  }

  static _navigateTo(obj, path) {
    let current = obj;
    for (const key of path) {
      if (current == null) return null;
      current = current[key];
    }
    return current;
  }
}

// Cross-Layer Consistency Checker
export class CrossLayerValidator {
  static validate(configs) {
    const issues = [];
    const { ui, api, db, auth, businessLogic } = configs;

    // 1. Check API endpoints reference valid DB entities
    if (api?.endpoints && db?.tables) {
      const tableNames = new Set(db.tables.map(t => t.name.toLowerCase()));
      for (const ep of api.endpoints) {
        if (ep.relatedEntity && ep.relatedEntity !== 'unknown' && ep.relatedEntity !== 'auth') {
          const entityTable = ep.relatedEntity.toLowerCase() + 's';
          const entitySingular = ep.relatedEntity.toLowerCase();
          if (!tableNames.has(entityTable) && !tableNames.has(entitySingular) && !tableNames.has(ep.relatedEntity.toLowerCase())) {
            issues.push({
              type: 'api-db-mismatch',
              severity: 'error',
              message: `API endpoint "${ep.path}" references entity "${ep.relatedEntity}" but no matching DB table found`,
              layers: ['api', 'db'],
              fix: 'auto'
            });
          }
        }
      }
    }

    // 2. Check UI data sources reference valid API endpoints
    if (ui?.pages && api?.endpoints) {
      const apiPaths = new Set(api.endpoints.map(e => e.path));
      for (const page of ui.pages) {
        for (const comp of (page.components || [])) {
          if (comp.dataSource?.endpoint && !apiPaths.has(comp.dataSource.endpoint)) {
            issues.push({
              type: 'ui-api-mismatch',
              severity: 'warning',
              message: `UI component "${comp.id}" on page "${page.name}" references non-existent API endpoint "${comp.dataSource.endpoint}"`,
              layers: ['ui', 'api'],
              fix: 'auto'
            });
          }
        }
      }
    }

    // 3. Check auth roles are consistent across layers
    if (auth?.roles) {
      const authRoleNames = new Set(auth.roles.map(r => r.name.toLowerCase()));

      // Check UI page roles
      if (ui?.pages) {
        for (const page of ui.pages) {
          for (const role of (page.requiredRoles || [])) {
            if (!authRoleNames.has(role.toLowerCase())) {
              issues.push({
                type: 'ui-auth-mismatch',
                severity: 'error',
                message: `UI page "${page.name}" requires role "${role}" which is not defined in auth config`,
                layers: ['ui', 'auth'],
                fix: 'auto'
              });
            }
          }
        }
      }

      // Check API endpoint roles
      if (api?.endpoints) {
        for (const ep of api.endpoints) {
          for (const role of (ep.auth?.roles || [])) {
            if (!authRoleNames.has(role.toLowerCase())) {
              issues.push({
                type: 'api-auth-mismatch',
                severity: 'error',
                message: `API endpoint "${ep.path}" references role "${role}" not in auth config`,
                layers: ['api', 'auth'],
                fix: 'auto'
              });
            }
          }
        }
      }
    }

    // 4. Check DB foreign keys reference valid tables
    if (db?.tables) {
      const tableNames = new Set(db.tables.map(t => t.name));
      for (const table of db.tables) {
        for (const col of table.columns) {
          if (col.references?.table && !tableNames.has(col.references.table)) {
            issues.push({
              type: 'db-self-mismatch',
              severity: 'error',
              message: `Table "${table.name}" column "${col.name}" references non-existent table "${col.references.table}"`,
              layers: ['db'],
              fix: 'manual'
            });
          }
        }
      }
    }

    // 5. Check business logic references valid entities
    if (businessLogic?.rules && db?.tables) {
      const tableNames = new Set(db.tables.map(t => t.name.toLowerCase()));
      for (const rule of businessLogic.rules) {
        for (const action of (rule.actions || [])) {
          if (action.target && !tableNames.has(action.target.toLowerCase()) && action.target !== 'system') {
            issues.push({
              type: 'logic-db-mismatch',
              severity: 'warning',
              message: `Business rule "${rule.name}" targets entity "${action.target}" with no matching DB table`,
              layers: ['businessLogic', 'db'],
              fix: 'auto'
            });
          }
        }
      }
    }

    return {
      consistent: issues.filter(i => i.severity === 'error').length === 0,
      issues,
      autoFixable: issues.filter(i => i.fix === 'auto').length,
      summary: `${issues.length} issues found (${issues.filter(i => i.severity === 'error').length} errors, ${issues.filter(i => i.severity === 'warning').length} warnings)`
    };
  }

  // Auto-fix cross-layer issues
  static autoFix(configs, issues) {
    const fixed = JSON.parse(JSON.stringify(configs));
    const repairs = [];

    for (const issue of issues.filter(i => i.fix === 'auto')) {
      switch (issue.type) {
        case 'ui-auth-mismatch': {
          // Add missing role to auth
          const roleName = issue.message.match(/role "(\w+)"/)?.[1];
          if (roleName && fixed.auth) {
            fixed.auth.roles.push({ name: roleName, description: `Auto-added role: ${roleName}`, isDefault: false });
            repairs.push(`Added missing role "${roleName}" to auth config`);
          }
          break;
        }
        case 'api-auth-mismatch': {
          const roleName = issue.message.match(/role "(\w+)"/)?.[1];
          if (roleName && fixed.auth) {
            fixed.auth.roles.push({ name: roleName, description: `Auto-added role: ${roleName}`, isDefault: false });
            repairs.push(`Added missing role "${roleName}" to auth config`);
          }
          break;
        }
        case 'api-db-mismatch': {
          // Add missing table to DB
          const entity = issue.message.match(/entity "(\w+)"/)?.[1];
          if (entity && fixed.db) {
            fixed.db.tables.push({
              name: entity.toLowerCase() + 's',
              columns: [
                { name: 'id', type: 'uuid', primaryKey: true },
                { name: 'created_at', type: 'timestamp', default: 'now()' }
              ],
              timestamps: true
            });
            repairs.push(`Added missing table "${entity.toLowerCase()}s" to DB schema`);
          }
          break;
        }
      }
    }

    return { configs: fixed, repairs };
  }
}
